import json
import requests

body = {
    "msg_type": "post",
    "content": {
        "post": {
            "zh_cn": {
                "title": "《郑公泽指数投资每日资讯 | 2026-05-09》",
                "content": [
                    [{"tag": "text", "text": "【每日风险监控提醒】本报告内容仅供参考，不构成投资建议。指数投资有风险，请理性决策。"}],
                    None,
                    [{"tag": "text", "text": "一、今日市场速览", "text_style": {"bold": True, "text_size": "lg"}}],
                    None,
                    [{"tag": "text", "text": "5月9日，A股市场在多重政策利好提振下延续结构性行情。美股隔夜大幅收涨，纳指涨1.71%创历史新高，标普500涨0.84%创历史新高，连续六周上涨，科技芯片板块领涨全场。外资持续流入A股，北向资金5月以来累计净流入超200亿元，四部门联合出手释放AI产业重磅政策，AI+能源、AI智能体、6G通信、半导体高端制造成为市场主线。特朗普10%关税被法院裁定无效，中美贸易环境边际改善。"}],
                    None,
                    [{"tag": "text", "text": "二、宽基指数重要资讯", "text_style": {"bold": True, "text_size": "lg"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 美股科技股强势爆发，纳指、标普500双双创历史新高", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：5月8日（北京时间5月9日凌晨）美股三大指数集体收涨，纳指大涨1.71%至26247.08点创历史新高，标普500涨0.84%至7398.93点创历史新高，连续第六周上涨。道指微涨0.02%。科技芯片板块成为全场最大赢家，超120亿美元流入科技板块ETF。"}],
                    [{"tag": "text", "text": "关联ETF：创业板ETF(159915) | 沪深300ETF(510300)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ 北向资金持续流入，5月以来累计净买入超200亿元", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：北向资金5月以来持续加仓A股，累计净流入超200亿元，重点布局低估值政策受益股。公募基金加速调仓，减仓高位纯AI题材股，加仓储能、智能电网、绿电等低位赛道。外资对A股核心资产偏好上升。"}],
                    [{"tag": "text", "text": "关联ETF：沪深300ETF(510300) | 创业板ETF(159915)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 四部门联合出手，AI产业政策利好密集落地", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：5月9日，四部门联合发布AI产业重磅政策，明确29项重点任务，制定2027年、2030年两大阶段硬目标。核心解决AI产业高耗电痛点，要求新建算力中心绿电占比必须达标。储能板块迎算力中心配储+新能源储能双重订单增长，业绩预计增长50%-100%。"}],
                    [{"tag": "text", "text": "关联ETF：创业板ETF(159915) | 沪深300ETF(510300)　　影响方向：利好　　⚠️高风险关注", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "4️⃣ 特朗普10%关税被法院裁定无效，贸易环境边际改善", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：纽约联邦法院裁定特朗普政府2月份征收的10%全球进口关税缺乏法律依据，白宫公告无效。尽管中美关税战按下暂停键，但美方关税政策存在法律漏洞，市场对中美关系改善预期升温。"}],
                    [{"tag": "text", "text": "关联ETF：沪深300ETF(510300) | 中证500ETF(510500)　　影响方向：利好"}],
                    None,
                    [{"tag": "text", "text": "5️⃣ 中国黄金储备连续18个月增持，央行稳健操作", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：中国4月末黄金储备报7464万盎司，环比增加26万盎司，为连续第18个月增持。新兴国家央行持续增持黄金为金价提供中长期底部支撑，反映全球去美元化趋势下央行资产配置优化。"}],
                    [{"tag": "text", "text": "关联ETF：沪深300ETF(510300)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "6️⃣ A股市场主线明确，四大方向受资金青睐", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：市场主线彻底明确为四大方向：AI+能源（储能、智能电网）、AI智能体、6G通信、半导体高端制造。游资提前潜伏相关细分赛道，主力资金全天净买入超520亿元，聚焦科技成长赛道。"}],
                    [{"tag": "text", "text": "关联ETF：创业板ETF(159915) | 中证500ETF(510500)　　影响方向：利好"}],
                    None,
                    [{"tag": "text", "text": "7️⃣ 美股科技强周期弱，对A股科技板块形成映射效应", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：美股AI需求仍是核心，英伟达等AI芯片龙头表现强劲，但模拟和汽车芯片相对落后。分析师指出美股科技强周期弱格局对A股整体偏多，利好半导体/AI/算力/光模块，能源承压，消费分化。"}],
                    [{"tag": "text", "text": "关联ETF：创业板ETF(159915) | 沪深300ETF(510300)　　影响方向：利好"}],
                    None,
                    [{"tag": "text", "text": "8️⃣ 商业航天概念爆发，成为市场结构性亮点", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：5月8日A股商业航天概念板块异军突起，成为全场唯一主线。政策、技术、资本共振推动商业航天产业发展，多家产业链公司获得资金关注，带动相关板块活跃度提升。"}],
                    [{"tag": "text", "text": "关联ETF：中证500ETF(510500) | 创业板ETF(159915)　　影响方向：利好"}],
                    None,
                    [{"tag": "text", "text": "9️⃣ 美债收益率回落，全球避险情绪降温", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：地缘局势不确定性推升避险需求，资金涌入美债。随着美债收益率回落，市场风险偏好回升，投资者提前布局等待非农数据，美国就业降温预期升温。"}],
                    [{"tag": "text", "text": "关联ETF：沪深300ETF(510300)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "🔟 芯片板块估值扩张，分析师分歧加大需关注", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：芯片板块估值扩张，分析师分歧加大，投资者关注度提升。市场宽度偏窄，仅部分成分股跑赢指数，需警惕估值回调风险。"}],
                    [{"tag": "text", "text": "关联ETF：创业板ETF(159915)　　影响方向：中性　　⚠️高风险关注", "text_style": {"text_color": "orange"}}],
                    None,
                    [{"tag": "text", "text": "三、行业指数重要资讯", "text_style": {"bold": True, "text_size": "lg"}}],
                    None,
                    [{"tag": "text", "text": "【恒生互联网ETF (513330)】", "text_style": {"bold": True, "text_color": "blue"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 阿里、腾讯5月7日涨超3%，港股互联网板块强劲", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：5月7日午后，阿里巴巴-W、百度集团-SW、腾讯控股延续涨势，均涨超3%。恒生互联网ETF华夏(513330)维持上涨，字节豆包宣布付费推动港股互联网板块活跃。"}],
                    [{"tag": "text", "text": "关联ETF：恒生互联网ETF(513330)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ 阿里、腾讯Q1财报将于5月13日披露，关注业绩超预期可能", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：阿里巴巴、腾讯控股将于5月13日晚披露第一季度财报，百度集团将于5月18日公布财报，京东集团将于5月12日披露。市场对科技巨头业绩超预期抱有期待，港股互联网板块有望受益。"}],
                    [{"tag": "text", "text": "关联ETF：恒生互联网ETF(513330)　　影响方向：中性　　⚠️高风险关注", "text_style": {"text_color": "orange"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 港股IPO 2026年预计3000亿，中概股回归提速", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：安永预计2026年港股IPO将保持热度，中概股回归与特专科技公司（AI、生物医药等）将共同构成重要上市来源。港交所持续推进上市制度优化，进一步加强香港证券市场效率及竞争力。"}],
                    [{"tag": "text", "text": "关联ETF：恒生互联网ETF(513330)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "4️⃣ 港股科技板块内部分化，阿里百度领涨腾讯美团承压", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年5月港股开门红，但科技板块内部出现显著分化。阿里巴巴与百度展现强劲上涨动能，明显优于腾讯、京东及美团的震荡或回调。投资者需关注个股走势差异对ETF的影响。"}],
                    [{"tag": "text", "text": "关联ETF：恒生互联网ETF(513330)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "【信息技术ETF (159939)】", "text_style": {"bold": True, "text_color": "blue"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 半导体板块五重利好共振，进入超级上行周期", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年Q2半导体板块迎来周期反转+AI需求爆发+政策强力护航+国产替代提速+存储价格暴涨五重利好共振，行业正式告别下行周期，进入AI算力主导的超级上行周期，全产业链景气度回升。"}],
                    [{"tag": "text", "text": "关联ETF：信息技术ETF(159939)　　影响方向：利好　　⚠️高风险关注", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ AI需求推动科技ETF吸金，超120亿美元流入", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：随着美债收益率回落，超120亿美元流入科技板块ETF。AI需求仍是核心推动力，英伟达等AI芯片龙头表现强劲，带动整个科技板块估值扩张。"}],
                    [{"tag": "text", "text": "关联ETF：信息技术ETF(159939) | 创业板ETF(159915)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 算力中心政策利好密集，新建项目绿电要求明确", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：四部门联合发布AI产业重磅政策，明确新建算力中心绿电占比必须达标。储能板块迎来算力中心配储+新能源储能双重订单增长，智能电网板块订单确定性强，估值处于历史底部，业绩弹性巨大。"}],
                    [{"tag": "text", "text": "关联ETF：信息技术ETF(159939) | 创业板ETF(159915)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "【医疗ETF (162412)】", "text_style": {"bold": True, "text_color": "blue"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 医疗器械行业迎政策红利，创新国产双发力", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年医疗器械行业政策方向明显调整，从压低价格的集采转变为优先支持创新、保障企业合理利润、帮助国产替代突破。创新医疗器械企业获得更多政策倾斜，行业迎来新一轮发展机遇。"}],
                    [{"tag": "text", "text": "关联ETF：医疗ETF(162412)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ 6类医用耗材大降价，5月下旬全国多地同步落地", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年5月下旬起，北京、江西、广东等全国多地将同步落地6类医用耗材集中带量采购结果，覆盖心脏、泌尿、先心病、神经等领域。手术费用预计可节省一半，对医疗板块盈利能力形成压制。"}],
                    [{"tag": "text", "text": "关联ETF：医疗ETF(162412)　　影响方向：利空　　⚠️高风险关注", "text_style": {"text_color": "red"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 上海医保新规5月落地，门诊配药自费比例调整", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年5月1日起上海正式执行全新集采药品医保支付新规，医生主动询问患者选择集采仿制药还是原研药，部分进口药自费金额明显上升。集采药品医保支付协同政策全国推广中。"}],
                    [{"tag": "text", "text": "关联ETF：医疗ETF(162412)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "【新能源汽车ETF (501057)】", "text_style": {"bold": True, "text_color": "blue"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 宁德时代全球份额39.2%稳居第一，储能业务爆发", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：宁德时代牢牢占据国内半壁江山，全球份额稳定在39.2%，远超比亚迪、LG新能源等所有同行。储能电池全球市占率连续五年第一，份额突破30%。2026年储能业务迎来爆发式增长，AI算力储能、电网大储、户用储能、工商业储能全面开花。"}],
                    [{"tag": "text", "text": "关联ETF：新能源汽车ETF(501057)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ 宁德时代+比亚迪合计市占率76.4%，行业集中度提升", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年一季度，宁德时代国内市占率44.3%，比亚迪32.1%，两家合计76.4%，行业集中度比2024年又提升了。前五强排位：宁德时代、比亚迪、中创新航、国轩高科等，行业竞争格局持续优化。"}],
                    [{"tag": "text", "text": "关联ETF：新能源汽车ETF(501057)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 宁德时代贵州二期启动，规划年产能30GWh", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：宁德时代贵州新能源动力及储能电池生产制造基地二期项目正式启动，规划设计年产能30GWh动力及储能电池。新能源汽车市场持续扩大，动力电池需求旺盛，龙头企业扩产加速。"}],
                    [{"tag": "text", "text": "关联ETF：新能源汽车ETF(501057)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "【酒ETF (512690)】", "text_style": {"bold": True, "text_color": "blue"}}],
                    None,
                    [{"tag": "text", "text": "1️⃣ 茅台价格5月9日稳中有升，市场行情整体向好", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年5月9日茅台行情价格上涨5款，下跌0款，与昨日行情相比总体上涨。茅台价格稳中有升，热门茅台酒价格保持坚挺，市场需求保持活跃。"}],
                    [{"tag": "text", "text": "关联ETF：酒ETF(512690)　　影响方向：利好", "text_style": {"text_color": "green"}}],
                    None,
                    [{"tag": "text", "text": "2️⃣ 五粮液发布会计差错更正公告，投资者维权进行中", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年4月30日晚，宜宾五粮液股份有限公司发布《关于前期会计差错更正的公告》，对2025年前三季度财务数据进行追溯调整，引发市场关注。投资者维权进展持续推进中，五粮液股价承压震荡筑底。"}],
                    [{"tag": "text", "text": "关联ETF：酒ETF(512690)　　影响方向：利空　　⚠️高风险关注", "text_style": {"text_color": "red"}}],
                    None,
                    [{"tag": "text", "text": "3️⃣ 高端白酒市场分化，茅台创新高与区域酒企承压并存", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年白酒股呈现冰火两重天格局，贵州茅台股价创新高，五粮液震荡筑底，区域酒企加速分化。最新财报与行业数据显示头部酒企竞争优势持续扩大，市场集中度提升。"}],
                    [{"tag": "text", "text": "关联ETF：酒ETF(512690)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "4️⃣ 白酒线下销售起量与股市走势背离，关注边际变化", "text_style": {"bold": True}}],
                    [{"tag": "text", "text": "摘要：2026年开年以来高端白酒线下销售起量，但股市依然走低。白酒出现线下实体市场与股市走势背离的诡异现象，1499元茅台在线下市场持续热销，需关注基本面变化向股价传导的时滞。"}],
                    [{"tag": "text", "text": "关联ETF：酒ETF(512690)　　影响方向：中性"}],
                    None,
                    [{"tag": "text", "text": "━━━━━━━━━━━━━━━━━━━━━━━━━━"}],
                    None,
                    [{"tag": "text", "text": "【免责声明】本报告仅供信息参考，不构成任何投资建议。指数投资存在风险，请根据自身风险承受能力理性决策。"}]
                ]
            }
        }
    }
}

url = "https://open.feishu.cn/open-apis/bot/v2/hook/78352ea0-ceee-4fd9-932b-dafabac15087"
headers = {"Content-Type": "application/json"}

response = requests.post(url, json=body, headers=headers)
print(f"Status Code: {response.status_code}")
print(f"Response: {response.text}")
